.DEFAULT_GOAL := compile_all

compile_all:
	gcc -Wall ./ipv6-tcp-client.c -o ./ipv6-tcp-client
	gcc -Wall ./ipv6-tcp-server.c -o ./ipv6-tcp-server
	gcc -Wall ./zadanie_04_client_ipv4-and-6.c -o ./zadanie_04_client_ipv4-and-6