.DEFAULT_GOAL := compile_all

compile_all:
	gcc -Wall ./ifinfo.c -o ./ifinfo
	gcc -Wall ./ifsetup.c -o ./ifsetup
	gcc -Wall ./ifaddrs.c -o ./ifaddrs
	gcc -Wall ./zadanie_02_ifinfo.c -o ./zadanie_02_ifinfo
	gcc -Wall ./zadanie_03_on_off.c -o ./zadanie_03_on_off
	gcc -Wall ./zadanie_04_promiscuous.c -o ./zadanie_04_promiscuous
	gcc -Wall ./zadanie_05_ifsetup_with_ip_mask.c -o ./zadanie_05_ifsetup_with_ip_mask