.DEFAULT_GOAL := compile_all

compile_all:
	gcc -Wall ./ethrecv.c -o ./ethrecv
	gcc -Wall ./ethsend.c -o ./ethsend
	gcc -Wall ./zadanie_03_snooper.c -o ./zadanie_03_snooper
	gcc -Wall ./zadanie_04_repeater.c -o ./zadanie_04_repeater