.DEFAULT_GOAL := compile_all

compile_all:
	gcc -Wall ./zadanie_07_udp_server.c -o ./zadanie_07_udp_server
	gcc -Wall ./udp-client.c -o ./udp-client
	gcc -Wall ./udp-server.c -o ./udp-server
	gcc -Wall ./zadanie_06_tcp_server.c -o ./zadanie_06_tcp_server