.DEFAULT_GOAL := compile_all

compile_all:
	gcc -Wall ./ipping.c -o ./ipping
	gcc -Wall ./zadanie_03_ipping.c -o ./zadanie_03_ipping
	gcc -Wall ./iprecv.c -o ./iprecv
	gcc -Wall ./ipsend.c -o ./ipsend
	gcc -Wall ./zadanie_04_ipforward.c -o ./zadanie_04_ipforward