.DEFAULT_GOAL := compile_all

compile_all:
	gcc -Wall ./socket-buffers.c -o ./socket-buffers
	gcc -Wall ./tcp-server.c -o ./tcp-server
	gcc -Wall ./tcp-client.c -o ./tcp-client
	gcc -Wall ./zadanie_04_setsockopt.c -o ./zadanie_04_setsockopt